### ISSUE TITLE
Panel isn't shown when the button is in the menu

### ISSUE THREAD

**Issue by freaktechnik** [ajsb85/firefox-addon-ubuntuve#1]
When in the menu the menu gets closed and the panel is never shown:

https://gfycat.com/CheapMetallicFallowdeer

**Comment by ajsb85** [comment]
Fixed, thanks. @freaktechnik 
![screen4](https://cloud.githubusercontent.com/assets/663460/14060134/e35496b6-f359-11e5-8135-7d0be4656f6c.png)
